// Generated by gencpp from file bair_car/sim_env.msg
// DO NOT EDIT!


#ifndef BAIR_CAR_MESSAGE_SIM_ENV_H
#define BAIR_CAR_MESSAGE_SIM_ENV_H

#include <ros/service_traits.h>


#include <bair_car/sim_envRequest.h>
#include <bair_car/sim_envResponse.h>


namespace bair_car
{

struct sim_env
{

typedef sim_envRequest Request;
typedef sim_envResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sim_env
} // namespace bair_car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bair_car::sim_env > {
  static const char* value()
  {
    return "b309b81746c8edad7c966dda272a1ed4";
  }

  static const char* value(const ::bair_car::sim_env&) { return value(); }
};

template<>
struct DataType< ::bair_car::sim_env > {
  static const char* value()
  {
    return "bair_car/sim_env";
  }

  static const char* value(const ::bair_car::sim_env&) { return value(); }
};


// service_traits::MD5Sum< ::bair_car::sim_envRequest> should match 
// service_traits::MD5Sum< ::bair_car::sim_env > 
template<>
struct MD5Sum< ::bair_car::sim_envRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bair_car::sim_env >::value();
  }
  static const char* value(const ::bair_car::sim_envRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bair_car::sim_envRequest> should match 
// service_traits::DataType< ::bair_car::sim_env > 
template<>
struct DataType< ::bair_car::sim_envRequest>
{
  static const char* value()
  {
    return DataType< ::bair_car::sim_env >::value();
  }
  static const char* value(const ::bair_car::sim_envRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bair_car::sim_envResponse> should match 
// service_traits::MD5Sum< ::bair_car::sim_env > 
template<>
struct MD5Sum< ::bair_car::sim_envResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bair_car::sim_env >::value();
  }
  static const char* value(const ::bair_car::sim_envResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bair_car::sim_envResponse> should match 
// service_traits::DataType< ::bair_car::sim_env > 
template<>
struct DataType< ::bair_car::sim_envResponse>
{
  static const char* value()
  {
    return DataType< ::bair_car::sim_env >::value();
  }
  static const char* value(const ::bair_car::sim_envResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAIR_CAR_MESSAGE_SIM_ENV_H
