// Generated by gencpp from file bair_car/sim_envResponse.msg
// DO NOT EDIT!


#ifndef BAIR_CAR_MESSAGE_SIM_ENVRESPONSE_H
#define BAIR_CAR_MESSAGE_SIM_ENVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <geometry_msgs/Pose.h>

namespace bair_car
{
template <class ContainerAllocator>
struct sim_envResponse_
{
  typedef sim_envResponse_<ContainerAllocator> Type;

  sim_envResponse_()
    : coll(false)
    , image()
    , depth()
    , pose()  {
    }
  sim_envResponse_(const ContainerAllocator& _alloc)
    : coll(false)
    , image(_alloc)
    , depth(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _coll_type;
  _coll_type coll;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _depth_type;
  _depth_type depth;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::bair_car::sim_envResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bair_car::sim_envResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sim_envResponse_

typedef ::bair_car::sim_envResponse_<std::allocator<void> > sim_envResponse;

typedef boost::shared_ptr< ::bair_car::sim_envResponse > sim_envResponsePtr;
typedef boost::shared_ptr< ::bair_car::sim_envResponse const> sim_envResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bair_car::sim_envResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bair_car::sim_envResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bair_car

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bair_car::sim_envResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bair_car::sim_envResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bair_car::sim_envResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bair_car::sim_envResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bair_car::sim_envResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bair_car::sim_envResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bair_car::sim_envResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0bb2dab39897d48a64e4bba523448fcc";
  }

  static const char* value(const ::bair_car::sim_envResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0bb2dab39897d48aULL;
  static const uint64_t static_value2 = 0x64e4bba523448fccULL;
};

template<class ContainerAllocator>
struct DataType< ::bair_car::sim_envResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bair_car/sim_envResponse";
  }

  static const char* value(const ::bair_car::sim_envResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bair_car::sim_envResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool coll\n\
sensor_msgs/Image image\n\
sensor_msgs/Image depth\n\
geometry_msgs/Pose pose\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::bair_car::sim_envResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bair_car::sim_envResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coll);
      stream.next(m.image);
      stream.next(m.depth);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sim_envResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bair_car::sim_envResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bair_car::sim_envResponse_<ContainerAllocator>& v)
  {
    s << indent << "coll: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.coll);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "depth: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.depth);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAIR_CAR_MESSAGE_SIM_ENVRESPONSE_H
